version: '3'

networks:
  app-network:
    driver: bridge

services:
  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - app-network
    volumes:
      - ./.cache/pgdata:/var/lib/postgresql